Fixed trace_collector error in multi_server benchmark file
Fixed the `benchmark_multi_server.py` to match the constructor of "BenchmarkReport" by passing the "trace_collector".

Previously, running this file would result in `TypeError: BenchmarkReport.__init__() missing 1 required positional arguement: 'trarce collector`